### ISSUE TITLE
what's this about

### ISSUE THREAD

**Issue by jalasem** [SchoolRants/SchoolRants#1]
This repo name sounds interesting

**Comment by ooade** [comment]
@jalasem Yeah. It's going to be cool. Here's the description:

> A PLATFORM WHERE STUDENTS AND OTHER STAKEHOLDERS CAN ANONYMOUSLY REVIEW SCHOOLS AND THEIR MANAGEMENT
> 
> It is one thing to rant, it is another for us to be clear about what the shared understanding of a ‘good school’ is. Suggested scoring criteria include quality of infrastructure, faculty, effectiveness etc. The solution needs to be able to allow for anonymous reporting of issues e.g sexual harassment, extortion, method of teachers, trainers, lecturers and must be very practical and easy to scale in Nigeria.

I once had in mind to do the project then [Sauce Code](saucecode.xyz) brought it up again, making it a lil bit clear. We(I and a Classmate) will build this with Vue.js and Node.js. If you'd like to hop it, feel free.

We won't say anything about this project on social media tho, until it's completed (all test passes, everything works normal, and it's gone through evaluation from beta testers).

**Comment by jalasem** [comment]
Alright, thanks for the explanation. This sounds cool.
